logman.settings:
  type: mapping
  label: Settings
  mapping:
    logman_gelf_host:
      type: string
    logman_gelf_port:
      type: string
    logman_gelf_node:
      type: string
    logman_items_per_page:
      type: string
    logman_watchdog_log_type:
      type: string
    logman_apache_log_path:
      type: string
    logman_apache_read_limit:
      type: integer
    logman_show_page_statistics:
      type: integer
    logman_page_statistics_duration:
      type: integer
    logman_page_statistics_duration_unit:
      type: string
    logman_google_chart_api_url:
      type: string
    logman_log_item_per_page:
      type: integer
